### ISSUE TITLE
Obfuscated C

### ISSUE THREAD

**Issue by parth-io** [nushackers/fh-250-puzzles#1]
What does this obfuscated C code do? Make a guess as to its logic/why it works.

```
int main(int b,char**i){long long n=B,a=I^n,r=(a/b&a)>>4,y=atoi(*++i),_=(((a^n/b)*(y>>T)|y>>S)&r)|(a^r);printf("%.8s\n",(char*)&_);}
```

To compile
`clang -include stdio.h -include stdlib.h -Wall -Weverything -pedantic -DB=6945503773712347754LL -DI=5859838231191962459LL -DT=0 -DS=7 -o prog prog.c`

The compile-time flags of `-DB, -DI, -DT, -DS` are passed to the program.

Hint: Look at the bitwise operations and split it out by line! Look at the variable `_`.

More details here: [burton IOCC](https://ioccc.org/2020/burton/)

**Comment by joshcangit** [comment]
It converts the first argument, an integer, into **8 bit binary**.
Numbers 0 and 256 convert to `00000000`.
Negative numbers convert to `11111111`.

Executing without arguments will give a `Segmentation fault (core dumped)` error.
Compilation generates a warning, which can be ignored.
```
prog.c:1:68: warning: unsafe pointer arithmetic [-Wunsafe-buffer-usage]
    1 | int main(int b,char**i){long long n=B,a=I^n,r=(a/b&a)>>4,y=atoi(*++i),_=(((a^n/b)*(y>>T)|y>>S)&r)|(a^r);printf("%.8s\n",(char*)&_);}
      |                                                                    ^
1 warning generated.
```

**Comment by tanyyyming** [comment]
It converts a non-negative integer `x` to the binary representation of `x % 256`. 
It converts a negative integer to `11111111`
It converts an integer and any character separated with whitespace (e.g. `./prog 3 randomstuff`) to `30"31331`

**Comment by sg-incognito** [comment]
![image](https://github.com/nushackers/fh-250-puzzles/assets/39517980/c89a65a7-4f18-44f1-9389-300c4dba37c7)
 
With a non-zero argument input, the code returns 8 characters, based on the flow seen in the image. 

With zero arguments, it throws a segmentation fault.

argc represents the number of arguments passed to the program. atoi(argv[1]) converts the argument (string) to an integer

**Comment by parth-io** [comment]
Unfortunately, we could not figure this out too.

There are some hints [here](https://ioccc.org/2020/burton/) that emphasise certain binary operations.

There is a trace of the math [here](https://hesimsek.com/blog/2022/10/05/analysis-of-a-winner-from-obfuscated-c-code-contest/).
