### ISSUE TITLE
Code Golf: Missing Digit

### ISSUE THREAD

**Issue by parth-io** [nushackers/fh-250-puzzles#2]
Given 9 digits from 0 to 9, write the shortest code you can in Python or C to find the missing digit.

Example:
Input :      756432098
Output:   1

**Comment by sg-incognito** [comment]
while 1:print(45-sum(map(int,input())))

39 bytes

**Comment by joeng03** [comment]
print(next(iter(set('0123456789') - set(input()))))

**Comment by parth-io** [comment]
Typical answer: `while 1:print(45-sum(map(int,input())))`
Using some math trickery: `while 1:print(-int(input(),16)%15)`
