### ISSUE TITLE
Code Golf: Collatz

### ISSUE THREAD

**Issue by parth-io** [nushackers/fh-250-puzzles#4]
The Collatz conjecture states that, for any positive integer n, it will eventually reach 1 by repeatedly applying the following procedure:

- If n is even, divide it by 2.
- If n is odd, multiply by 3 and then add 1.
The number of steps needed for n to reach 1 is called its stopping time. For example, the stopping time of 10 is six:

10 → 5 → 16 → 8 → 4 → 2 → 1

Print the stopping times of all the numbers from 1 to 1,000 inclusive, each on their own line.

**Comment by tanyyyming** [comment]
```python
for i in range(1, 1001):
    count = 0
    while i != 1:
        i = i / 2 if i % 2 == 0 else 3 * i + 1
        count += 1
    print(count)
```
136 bytes

**Comment by sg-incognito** [comment]
```
for i in range(1,1001):
    c=0
    while i!=1:
        i=i/2 if (i%2==0) else 3*i+1
        c+=1
    print(c)
```

115 bytes

**Comment by iaxon** [comment]
for i in range(1,1001):
    c=0
    while i>1:c+=1; i=i/2 if i%2==0 else i*3+1
    print(c) 
    
93 bytes

**Comment by samyipsh** [comment]
f = lambda i,c:c if i==1 else f(i/2 if i%2==0 else 3*i+1,c+1)
print([f(x,0) for x in range(1,101)])
