### ISSUE TITLE
Figure it out

### ISSUE THREAD

**Issue by parth-io** [nushackers/fh-250-puzzles#5]
What does this code do? Explain why this program works.

```
  #include <stdio.h>
  #include <stdlib.h>

  #define SIZEOF(arr) (sizeof(arr)/sizeof(arr[0]))

  #define PrintInt(expr) printf("%s:%d\n",#expr,(expr))
  int main()
  {
      /* The powers of 10 */
      int pot[] = {
          0001,
          0010,
          0100,
          1000
      };
      int i;

      for(i=0;i<SIZEOF(pot);i++)
          PrintInt(pot[i]);
      return 0;
  }
```

**Comment by sg-incognito** [comment]
Prints 
pot[i]:1
pot[i]:8
pot[i]:64
pot[i]:1000

This is because with a leading 0, it is stored as octal

**Comment by joeng03** [comment]
In C, when a numeric literal has a leading zero, it is treated as an octal (base-8) constant. Therefore, 0010 is interpreted as octal 10, which is equivalent to decimal 8.
          0001 -> 1 base 8 -> 1 base 10
          0010 -> 10 base 8 -> 8 base 10
          0100 -> 100 base 8 -> 64 base 10
          1000 -> interpreted as 1000 base 10 as it has no leading zeroes

**Comment by VikramGoyal23** [comment]
Output:
pot[i]:1
pot[i]:8
pot[i]:64
pot[i]:1000
C interprets numeric literals with 0 as a prefix as an octal, while those without this prefix are treated as a decimal.

**Comment by iaxon** [comment]
C interprets numbers with a leading 0 as oktal. Thats why the first 3 numbers in the output get interpreted as oktal and the last one as decimal.
Length of shorter version: 201 bytes

**Comment by parth-io** [comment]
You guys got it
